### PR TITLE
atlasaction: added summary to migrate-lint

### PR DESCRIPTION
**Pull request by dorav**

### CODE REVIEW

**Comment by dorav** [comment]
Me too

**Comment by dorav** [comment]
Hello world!

**Comment by dorav** [comment]
Hello world!

**Comment by dorav** [comment]
Hello world!

**Comment by dorav** [comment]
Hello world!

**Comment by dorav** [comment]
Hello world!

**Comment by dorav** [comment]
Hello world!

**Comment by dorav** [comment]
# Atlas Lint Report
<div>Analyzed <strong>test-dir</strong>  </div><br>
<strong>Lint report <a href="https://ariga-dorav.atlasgo.cloud/ci-runs/8589935085">available here</a></strong>

**Review by a8m — APPROVED** [review]

**Pull request merged**
